# Generated by Django 4.2.9 on 2026-04-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_rename_anio_vigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('tipo', models.CharField(choices=[('ACADEMICO', 'Académico'), ('INSCRIPCION', 'Inscripción'), ('FERIADO', 'Feriado'), ('EXAMEN', 'Examen')], default='ACADEMICO', max_length=20, verbose_name='Tipo de Evento')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='inscripcion.periodoacademico', verbose_name='Periodo Académico')),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['fecha'],
            },
        ),
    ]
