# Generated by Django 4.2.9 on 2026-04-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_eventocalendario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-fecha_inscripcion_realizada', '-fecha_inscripcion_asignada'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='tipo_proceso',
            field=models.CharField(choices=[('INSCRIPCION', 'Inscripción'), ('ADICION', 'Adición'), ('RETIRO', 'Retiro')], default='INSCRIPCION', max_length=20, verbose_name='Proceso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='via',
            field=models.CharField(choices=[('WEB', 'Web'), ('VENTANILLA', 'Ventanilla')], default='WEB', max_length=20, verbose_name='Vía'),
        ),
    ]
