# Generated by Django 4.2.9 on 2026-04-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_alter_inscripcion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertamateria',
            name='turno',
            field=models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], default='MAÑANA', max_length=20, verbose_name='Turno'),
        ),
    ]
