# Generated by Django 4.2.9 on 2026-02-13 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código de Carrera')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Carrera')),
                ('facultad', models.CharField(max_length=200, verbose_name='Facultad')),
                ('duracion_semestres', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Duración en Semestres')),
                ('activa', models.BooleanField(default=True, verbose_name='Carrera Activa')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('registro', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Registro Universitario')),
                ('documento_identidad', models.CharField(default='0', max_length=20, verbose_name='Documento de Identidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido Materno')),
                ('lugar_origen', models.CharField(max_length=200, verbose_name='Lugar de Origen')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Estudiante Activo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstudianteCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre_actual', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Semestre Actual')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('SEMIPRESENCIAL', 'Semipresencial'), ('VIRTUAL', 'Virtual')], default='PRESENCIAL', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_inscritos', to='inscripcion.carrera')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='inscripcion.estudiante')),
            ],
            options={
                'verbose_name': 'Carrera de Estudiante',
                'verbose_name_plural': 'Carreras de Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Código de Materia')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Materia')),
                ('creditos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Créditos')),
                ('horas_teoricas', models.IntegerField(default=0, verbose_name='Horas Teóricas')),
                ('horas_practicas', models.IntegerField(default=0, verbose_name='Horas Prácticas')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MateriaCarreraSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Semestre')),
                ('obligatoria', models.BooleanField(default=True, verbose_name='Materia Obligatoria')),
                ('habilitada', models.BooleanField(default=True, verbose_name='Materia Habilitada')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_semestre', to='inscripcion.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_semestre', to='inscripcion.materia')),
            ],
            options={
                'verbose_name': 'Materia por Carrera y Semestre',
                'verbose_name_plural': 'Materias por Carrera y Semestre',
                'ordering': ['semestre', 'materia__codigo'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código del Periodo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Periodo')),
                ('tipo', models.CharField(choices=[('1/2026', 'Primer Semestre 2026'), ('2/2026', 'Segundo Semestre 2026'), ('1/2025', 'Primer Semestre 2025'), ('2/2025', 'Segundo Semestre 2025')], max_length=10, verbose_name='Tipo de Periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=False, verbose_name='Periodo Activo')),
                ('inscripciones_habilitadas', models.BooleanField(default=False, verbose_name='Inscripciones Habilitadas')),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Plan')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('anio_vigencia', models.IntegerField(verbose_name='Año de Vigencia')),
                ('vigente', models.BooleanField(default=True, verbose_name='Plan Vigente')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='inscripcion.carrera')),
            ],
            options={
                'verbose_name': 'Plan de Estudios',
                'verbose_name_plural': 'Planes de Estudio',
                'ordering': ['-anio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='OfertaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=5, verbose_name='Grupo')),
                ('docente', models.CharField(default='Por designar', max_length=100, verbose_name='Docente')),
                ('horario', models.CharField(default='HORARIO A CONFIRMAR', max_length=100, verbose_name='Horario')),
                ('cupo_maximo', models.IntegerField(default=40, verbose_name='Cupo Máximo')),
                ('cupo_actual', models.IntegerField(default=0, verbose_name='Cupo Actual')),
                ('materia_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='inscripcion.materiacarrerasemestre')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='inscripcion.periodoacademico')),
            ],
            options={
                'verbose_name': 'Oferta de Materia',
                'verbose_name_plural': 'Ofertas de Materias',
                'ordering': ['materia_carrera__materia__codigo', 'grupo'],
                'unique_together': {('materia_carrera', 'periodo', 'grupo')},
            },
        ),
        migrations.AddField(
            model_name='materiacarrerasemestre',
            name='plan_estudios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_semestre', to='inscripcion.planestudios'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion_asignada', models.DateField(verbose_name='Fecha de Inscripción Asignada')),
                ('fecha_inscripcion_realizada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inscripción Realizada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Estado de Bloqueo')),
                ('motivo_bloqueo', models.TextField(blank=True, verbose_name='Motivo del Bloqueo')),
                ('boleta_generada', models.BooleanField(default=False, verbose_name='Boleta Generada')),
                ('numero_boleta', models.CharField(blank=True, max_length=50, verbose_name='Número de Boleta')),
                ('estudiante_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='inscripcion.estudiantecarrera')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='inscripcion.periodoacademico')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion_asignada'],
                'unique_together': {('estudiante_carrera', 'periodo_academico')},
            },
        ),
        migrations.AddField(
            model_name='estudiantecarrera',
            name='plan_estudios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscripcion.planestudios'),
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Aplicado')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inscripcion.boleta')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletas', to='inscripcion.conceptopago')),
            ],
            options={
                'verbose_name': 'Detalle de Boleta',
                'verbose_name_plural': 'Detalles de Boleta',
            },
        ),
        migrations.AddField(
            model_name='boleta',
            name='inscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta_pago', to='inscripcion.inscripcion'),
        ),
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FINANCIERO', 'Deuda Financiera'), ('ACADEMICO', 'Bloqueo Académico'), ('ADMINISTRATIVO', 'Bloqueo Administrativo'), ('DISCIPLINARIO', 'Bloqueo Disciplinario')], max_length=20, verbose_name='Tipo de Bloqueo')),
                ('motivo', models.TextField(verbose_name='Motivo del Bloqueo')),
                ('fecha_bloqueo', models.DateField(auto_now_add=True, verbose_name='Fecha de Bloqueo')),
                ('fecha_desbloqueo_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Desbloqueo Estimada')),
                ('activo', models.BooleanField(default=True, verbose_name='Bloqueo Activo')),
                ('resuelto', models.BooleanField(default=False, verbose_name='Bloqueo Resuelto')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estudiante_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='inscripcion.estudiantecarrera')),
            ],
            options={
                'verbose_name': 'Bloqueo',
                'verbose_name_plural': 'Bloqueos',
                'ordering': ['-fecha_bloqueo'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='materiacarrerasemestre',
            unique_together={('carrera', 'plan_estudios', 'materia', 'semestre')},
        ),
        migrations.CreateModel(
            name='InscripcionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, default='A', max_length=5, verbose_name='Grupo')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_inscritas', to='inscripcion.inscripcion')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_directas', to='inscripcion.materia')),
                ('oferta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='inscripcion.ofertamateria')),
            ],
            options={
                'verbose_name': 'Materia Inscrita',
                'verbose_name_plural': 'Materias Inscritas',
                'unique_together': {('inscripcion', 'oferta')},
            },
        ),
    ]
