# Generated by Django 4.2.9 on 2026-03-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planestudios',
            options={'ordering': ['anio_vigencia'], 'verbose_name': 'Plan de Estudios', 'verbose_name_plural': 'Planes de Estudio'},
        ),
    ]
